### ISSUE TITLE
Aula 6

### ISSUE THREAD

**Issue by eliasfadel** [courselab/hello-world-eliasfadel#2]
Professor, eu tava fazendo juntamente com a aula a programação das variaveis usando o code Blocks e quando uso a função float numa variavel x, ao pedir ela no printf ela retorna um falor absurdo que nao condiz com o que coloquei, como faço para verificar o problema ou corrigir? 

[Programação.zip](https://github.com/courselab/hello-world-eliasfadel/files/4587776/Programacao.zip)

**Comment by monacofj** [comment]
Olá

Olhei seu código. Quando você compila o programa, possivelmente na aba de mensagens do compilador você pode ver um warning como este

``` 
Aula_6.c: In function ‘main’:
Aula_6.c:13:44: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘double’ [-Wformat=]
   13 |     printf ("a vale %d, b vale %d, x vale %d\n", a, b, x);
      |                                           ~^           ~
      |                                            |           |
      |                                            int         double
      |                                           %f
``` 
A dica está aí. No template de formação usado pela `prntf`, o símbolo `%d` significa que o correspondente argumento deve ser interpretado como um `int`. Para que seja interpretado como um `float`, você deve utilizar `%f`.  Modifique seu programa e teste novamente. Se der certo, feche essa issue.

Qualquer coisa, mantenha aberta e pergunte à vontade.
